language: php

php:
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer

before_install:
  - composer self-update
  - composer clear-cache

install:
  composer update --no-interaction --no-ansi --optimize-autoloader --prefer-dist

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse
  - ./vendor/bin/phpunit